### PR TITLE
Updated URL_RAW_BASE

### PR DESCRIPTION
**Pull request by ChrisKoh83**

### CODE REVIEW

**Comment by awalasz** [comment]
@Kanga-Who I meet the same issue with this script.
The current script erases all my configs, replacing its content with "404: Not Found", returned by:
```
URL_RAW_BASE="https://raw.githubusercontent.com/home-assistant/supervised-installer/master/files"
```
I lost `/etc/network/interfaces`, `/etc/NetworkManager/NetworkManager.conf`, and probably all other touched files.

**Comment by Kanga-Who** [comment]
@awalasz That script is no longer used, follow the instructions as you will notice it now uses a .deb file.

**Comment by awalasz** [comment]
@Kanga-Who Thanks for replying - I will read it carefully. But for the context of my case - I was following a tutorial that leads to your script directly with curl:
`curl -sL "https://raw.githubusercontent.com/Kanga-Who/home-assistant/master/supervised-installer.sh" | bash -s`

That really could mess up with the configs. @ChrisKoh83 - I would like to thank you - I found the proper files and was able to restore my network connection thanks to this PR :)

**Comment by Kanga-Who** [comment]
> I was following a tutorial that leads to your script directly with curl:

The guide states the following;

```
Section 3 – Install Home Assistant Supervised
.
.
.

Execute the following commands one at a time.

wget https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb

dpkg -i homeassistant-supervised.deb
```

**Comment by awalasz** [comment]
That's true. I only described my case and why I used that deprecated script. I mean the other tutorial, from another author probably, which suggests using your work :) 
I will try to let him know.

**Pull request closed without merging**
